### PR TITLE
add nb

### PR DESCRIPTION
**Pull request by derekflint**

### CODE REVIEW

**Comment by IgorFlint** [comment]
what's the difference between auger.yaml and auger_iris.yaml? Do we need both of them?

**Comment by derekflint** [comment]
no, let me push a quick update

**Comment by derekflint** [comment]
@IgorFlint can you test out this notebook. I am getting error starting experiment now and its probably easier if you just verify this code works.

**Comment by IgorFlint** [comment]
Will do it asap, after a meeting I'm attending now.

**Comment by IgorFlint** [comment]
@derekflint, for now I confirm that code fails. For me even before the experiment start, on DataSet creation with `worker_count is required` error. Seems to be a configuration issue.
Will get back tomorrow and check config and application

**Comment by holyketzer** [comment]
have the same issue, it should work due to https://github.com/deeplearninc/auger-ai/blob/master/auger/api/cloud/cluster.py#L54

**Pull request closed without merging**
